### ISSUE TITLE
GET Stats API: Add memory usage and loadavg data

### ISSUE THREAD

**Issue by xamfy** [xamfy/x-server-stats#14]
Currently only cpu stats are coming in the API response, the loadavg and memory usage values are hard coded. We need to fix this and look for more data that we can add in the API response. The same change will have to be done for index_stats page that returns the data in HTML form over HTTP.

We can research more about the [sysinfo](https://github.com/GuillaumeGomez/sysinfo) package as well.

We can prepare a list of stats that are interesting and pick and choose from that list.

**Comment by ChellappanRajan** [comment]
Please assign this issue on my name.

**Comment by ChellappanRajan** [comment]
Hi @xamfy  Could you please help me on this issue:
Currently I am trying to define custom struct for load_avg. However when I use Load_avg custom struct inside Stats struct I am getting below error.

`the trait bound `model::Load_avg: Clone` is not satisfied`


![image](https://user-images.githubusercontent.com/22997191/194498944-ee4bf9be-e79f-4755-a9e5-48f0eafd0c46.png)

**Comment by xamfy** [comment]
@ChellappanRajan Can you try removing `Clone` from the derive macro.

**Comment by ChellappanRajan** [comment]
Getting below error now: 

![image](https://user-images.githubusercontent.com/22997191/194565533-2eadf906-529e-4203-8a48-af1aff3947b4.png)

**Comment by xamfy** [comment]
@ChellappanRajan Since we're not using postgres for now, we can avoid using postgres mapper trait in the derive macro as well.

**Comment by ChellappanRajan** [comment]
Hi @xamfy Whatever I tried I had committed those code. If you get a chance please help me to fix.

**Comment by xamfy** [comment]
Is it in the new PR that you created just now or in some other branch?

**Comment by ChellappanRajan** [comment]
> Is it in the new PR that you created just now or in some other branch in your fork?

The one i created. I will push one more commit to it.

**Comment by ChellappanRajan** [comment]
This is the error I am unable to resolve.

The error occurs in **handler.rs**

```
pub trait Template
Main Template trait; implementations are generally derived

If you need an object-safe template, use [DynTemplate].

askama_derive
proc_macro Template
`stats::model::Loadavg` doesn't implement `std::fmt::Display`

`stats::model::Loadavg` cannot be formatted with the default formatter

help: the trait `std::fmt::Display` is not implemented for `stats::model::Loadavg`
note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
note: required because of the requirements on the impl of `std::fmt::Display` for
```
