### ISSUE TITLE
Create a stats GET API endpoint to fetch stats data over REST

### ISSUE THREAD

**Issue by xamfy** [xamfy/x-server-stats#5]
TODO:
- [ ] Add the stats API contract in the issue

**Comment by ChellappanRajan** [comment]
Hi @xamfy  I would like to take this issue, Could you please assign it to me and explain little more about this issue.

**Comment by xamfy** [comment]
Assigned it to you.

Basically we want to do the same thing that we talked about in the websocket task, but here it's just a GET API endpoint, to fetch the server stats (like cpu usage, memory usage, cpu load). We can start with these three first and then take it from there at a later point or discuss in the PR.
